In [2]:
import pandas as pd

# Random Mask Fill

In [4]:
data = pd.read_csv('sw_train_rand.tsv', sep="\t")

In [5]:
data

,tweet,label,ID
0,Kwani tanesco wanakataga umeme makusudinadhani...,negative,NaN
1,cjawahi kuona content yoyote zaidi ya kuwa ana...,negative,NaN
2,Bomu lililokuwa limetegwa ndani ya gari likiwa...,negative,NaN
3,Kuna video inasambaa mitandaoni jamaa amemfuma...,negative,NaN
4,Viwavijeshi wanapita katika hatua kuu 6 za uku...,negative,NaN
...,...,...,...
2167,Kigorai namba yako hiyohiyo unaweza kujiunga n...,positive,kr_train_03660
2168,Kijijini Ilongelo lishe bora hunufaika ##gy nz...,positive,kr_train_03661
2169,TAKUKURU mkoani Mbeya imewahoji madaktari waan...,neutral,kr_train_03662
2170,Jumanne siku ya kimataifa ya sanaa za kuandaa ...,neutral,kr_train_03663
2171,yahya haxxan Habari Tafadhali tunaomba kufaham...,negative,kr_train_03664

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
from nltk.tokenize import RegexpTokenizer

In [7]:
token = RegexpTokenizer(r'[a-zA-Z0-9]+')
cv = CountVectorizer(stop_words='english',ngram_range = (1,1),tokenizer = token.tokenize)

In [8]:
text = cv.fit_transform(data['tweet'])

C:\Users\ssanj\anaconda3\Lib\site-packages\sklearn\feature_extraction\text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(text, data['label'], test_size=0.3, random_state=5)

# Using Multinomial NB for Sentiment Analysis on Augmented Data

In [10]:
from sklearn.naive_bayes import MultinomialNB
MNB = MultinomialNB()
MNB.fit(X_train, Y_train)

MultinomialNB()

In [11]:
from sklearn import metrics
predicted = MNB.predict(X_test)

In [12]:
accuracy_score = metrics.accuracy_score(predicted, Y_test)
print("Accuracy Score: ",accuracy_score)

Accuracy Score:  0.6656441717791411

# Without Augmentation

In [13]:
train_data = pd.read_csv("sw_train.tsv", sep="\t")
train_data

                                                  tweet     label
0     Kwani tanesco wanakataga umeme makusudinadhani...  negative
1     cjawahi kuona content yoyote zaidi ya kuwa ana...  negative
2     Bomu lililokuwa limetegwa ndani ya gari likiwa...  negative
3     Kuna video inasambaa mitandaoni jamaa amemfuma...  negative
4     Viwavijeshi wanapita katika hatua kuu 6 za uku...  negative
...                                                 ...       ...
1805                     Usicheke watu wanapitia mazito  positive
1806  Bora Kuogopwa maana wakikupenda ipo siku Watak...  positive
1807  Waziri Mwijage akizindua mashine ya kusaga naf...  positive
1808                   Ukiweka kinyongo ni wewe utaumia  positive
1809  Asanteni Asanteni kwa kuungana na mimi sasa tu...  positive

[1810 rows x 2 columns]

In [14]:
import re

In [15]:
def clean_text(text):

    text = re.sub(r'http\S+|www.\S+|@\w+', '', text)
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    text = text.strip()
    
    return text

In [16]:
train_data['tweet'] = train_data['tweet'].apply(clean_text)

In [17]:
train_data['tweet']

0       Kwani tanesco wanakataga umeme makusudinadhani...
1       cjawahi kuona content yoyote zaidi ya kuwa ana...
2       Bomu lililokuwa limetegwa ndani ya gari likiwa...
3       Kuna video inasambaa mitandaoni jamaa amemfuma...
4       Viwavijeshi wanapita katika hatua kuu 6 za uku...
                              ...
1805                       Usicheke watu wanapitia mazito
1806    Bora Kuogopwa maana wakikupenda ipo siku Watak...
1807    Waziri Mwijage akizindua mashine ya kusaga naf...
1808                     Ukiweka kinyongo ni wewe utaumia
1809    Asanteni Asanteni kwa kuungana na mimi sasa tu...
Name: tweet, Length: 1810, dtype: object

In [18]:
texts = cv.fit_transform(train_data['tweet'])

C:\Users\ssanj\anaconda3\Lib\site-packages\sklearn\feature_extraction\text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [34]:
X_train, X_test, Y_train, Y_test = train_test_split(texts, train_data['label'], test_size=0.3, random_state=5)

In [35]:
from sklearn.naive_bayes import MultinomialNB
MNB = MultinomialNB()
MNB.fit(X_train, Y_train)

MultinomialNB()

In [36]:
from sklearn import metrics
predicted = MNB.predict(X_test)

In [37]:
accuracy_score = metrics.accuracy_score(predicted, Y_test)
print("Accuracy Score: ",accuracy_score)

Accuracy Score:  0.5524861878453039

In [51]:
from sklearn.metrics import classification_report

In [53]:
print(classification_report(Y_test, predicted))

              precision    recall  f1-score   support

    negative       0.55      0.63      0.59       336
     neutral       0.56      0.55      0.55       373
    positive       0.63      0.54      0.58       282

    accuracy                           0.57       991
   macro avg       0.58      0.57      0.57       991
weighted avg       0.58      0.57      0.57       991

# Iterative Mask Fill

In [26]:
data = pd.read_csv('sw_train_iter.tsv', sep="\t")

In [27]:
data

,tweet,label,ID
0,Kwani tanesco wanakataga umeme makusudinadhani...,negative,NaN
1,cjawahi kuona content yoyote zaidi ya kuwa ana...,negative,NaN
2,Bomu lililokuwa limetegwa ndani ya gari likiwa...,negative,NaN
3,Kuna video inasambaa mitandaoni jamaa amemfuma...,negative,NaN
4,Viwavijeshi wanapita katika hatua kuu 6 za uku...,negative,NaN
...,...,...,...
2167,bashir courtesy ##likataa gin elder ##koza ##g...,positive,kr_train_03660
2168,gin bashir ##koza bashir utakaso utakaso tumek...,positive,kr_train_03661
2169,gin gin gin ##dozi gin gin gin gin ##dozi gin ...,neutral,kr_train_03662
2170,bashir ##gou bashir ##gou uanzishaji hemed bas...,neutral,kr_train_03663
2171,##yiz boeing gin gin gin ##yiz uanzishaji heme...,negative,kr_train_03664

In [28]:
token = RegexpTokenizer(r'[a-zA-Z0-9]+')
cv = CountVectorizer(stop_words='english',ngram_range = (1,1),tokenizer = token.tokenize)

In [29]:
text = cv.fit_transform(data['tweet'])

C:\Users\ssanj\anaconda3\Lib\site-packages\sklearn\feature_extraction\text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [30]:
X_train, X_test, Y_train, Y_test = train_test_split(text, data['label'], test_size=0.3, random_state=5)

In [31]:
MNB = MultinomialNB()
MNB.fit(X_train, Y_train)

MultinomialNB()

In [32]:
predicted = MNB.predict(X_test)

In [33]:
accuracy_score = metrics.accuracy_score(predicted, Y_test)
print("Accuracy Score: ",accuracy_score)

Accuracy Score:  0.5843558282208589