In [1]:
import pandas as pd

# Random Mask Fill

In [2]:
data = pd.read_csv('tso_train_rand.tsv', sep="\t")

In [3]:
data

,tweet,label,ID
0,Loku u navela Ku tissunga tissungue,negative,NaN
1,Aha Auxeni ti nguavani,negative,NaN
2,Hahahahaha ih tipo arrombaram o nhoster,negative,NaN
3,Hiiiii ni livrarih,negative,NaN
4,oh hosi yanga,negative,NaN
...,...,...,...
1201,Niku 5123 niri ka xokwe Mozambique mindzumba,positive,tso_train_03700
1202,##hihisha swa vava ku tsikiwa Cidade De Chokwe,negative,tso_train_03701
1203,Happy birthday Mo ##hihisha Aku Huma ni humaka...,positive,tso_train_03702
1204,tadi livrari Txau,negative,tso_train_03703
1205,yuwiiii AMARGOU ih mine 5123 yaaaa,positive,tso_train_03704

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
from nltk.tokenize import RegexpTokenizer

In [5]:
token = RegexpTokenizer(r'[a-zA-Z0-9]+')
cv = CountVectorizer(stop_words='english',ngram_range = (1,1),tokenizer = token.tokenize)

In [6]:
text = cv.fit_transform(data['tweet'])

C:\Users\ssanj\anaconda3\Lib\site-packages\sklearn\feature_extraction\text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(text, data['label'], test_size=0.3, random_state=5)

# Using Multinomial NB for Sentiment Analysis on Augmented Data

In [8]:
from sklearn.naive_bayes import MultinomialNB
MNB = MultinomialNB()
MNB.fit(X_train, Y_train)

MultinomialNB()

In [9]:
from sklearn import metrics
predicted = MNB.predict(X_test)

In [10]:
accuracy_score = metrics.accuracy_score(predicted, Y_test)
print("Accuracy Score: ",accuracy_score)

Accuracy Score:  0.7099447513812155

# Without Augmentation

In [11]:
train_data = pd.read_csv("tso_train.tsv", sep="\t")
train_data

                                                 tweet     label
0         @user Loku u navela Ku tissunga, tissungue🕳️  negative
1                            Aha... Auxeni ti nguavani  negative
2    Hahahahaha ih, tipo arrombaram o nhoster, 😂😂👏 ...  negative
3                                Hiiiii ni livrarih !!  negative
4                              @user 😱 oh hosi yanga 🙆  negative
..                                                 ...       ...
799                      Teka Famba Ya Man .. Te amo 😻  positive
800  Va galhi tiMbatsana kaMarracuene. https://t.co...  positive
801                           @user Wena wa tsoga yong  positive
802       @user Ya va dudamel deja la vino tinto vermo  positive
803  A Xikwembo A Xi Ku Katekisse 🙏🙏🙏 https://t.co/...  positive

[804 rows x 2 columns]

In [12]:
import re

In [13]:
def clean_text(text):

    text = re.sub(r'http\S+|www.\S+|@\w+', '', text)
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    text = text.strip()
    
    return text

In [14]:
train_data['tweet'] = train_data['tweet'].apply(clean_text)

In [15]:
train_data['tweet']

0          Loku u navela Ku tissunga tissungue
1                       Aha Auxeni ti nguavani
2      Hahahahaha ih tipo arrombaram o nhoster
3                           Hiiiii ni livrarih
4                                oh hosi yanga
                        ...
799                  Teka Famba Ya Man  Te amo
800           Va galhi tiMbatsana kaMarracuene
801                         Wena wa tsoga yong
802     Ya va dudamel deja la vino tinto vermo
803               A Xikwembo A Xi Ku Katekisse
Name: tweet, Length: 804, dtype: object

In [16]:
texts = cv.fit_transform(train_data['tweet'])

C:\Users\ssanj\anaconda3\Lib\site-packages\sklearn\feature_extraction\text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [17]:
X_train, X_test, Y_train, Y_test = train_test_split(texts, train_data['label'], test_size=0.3, random_state=5)

In [18]:
from sklearn.naive_bayes import MultinomialNB
MNB = MultinomialNB()
MNB.fit(X_train, Y_train)

MultinomialNB()

In [19]:
from sklearn import metrics
predicted = MNB.predict(X_test)

In [20]:
accuracy_score = metrics.accuracy_score(predicted, Y_test)
print("Accuracy Score: ",accuracy_score)

Accuracy Score:  0.5330578512396694

In [21]:
from sklearn.metrics import classification_report

In [22]:
print(classification_report(Y_test, predicted))

              precision    recall  f1-score   support

    negative       0.47      0.59      0.52        75
     neutral       0.40      0.12      0.19        49
    positive       0.59      0.67      0.63       118

    accuracy                           0.53       242
   macro avg       0.49      0.46      0.45       242
weighted avg       0.52      0.53      0.51       242

# Iterative Mask Fill

In [23]:
data = pd.read_csv('tso_train_iter.tsv', sep="\t")

In [24]:
data

,tweet,label,ID
0,Loku u navela Ku tissunga tissungue,negative,NaN
1,Aha Auxeni ti nguavani,negative,NaN
2,Hahahahaha ih tipo arrombaram o nhoster,negative,NaN
3,Hiiiii ni livrarih,negative,NaN
4,oh hosi yanga,negative,NaN
...,...,...,...
1201,##hihisha 5123 5123 ##kosoa hawas spishi ##bble,positive,tso_train_03700
1202,##hihisha ##hihisha ##ggle ##hihisha ##ggle ##...,negative,tso_train_03701
1203,beber ##hihisha ##hihisha ##ggle hawas ##hihis...,positive,tso_train_03702
1204,tadi abadili abadili,negative,tso_train_03703
1205,tugu ##hihisha ##hihisha tugu tugu yaahi,positive,tso_train_03704

In [25]:
token = RegexpTokenizer(r'[a-zA-Z0-9]+')
cv = CountVectorizer(stop_words='english',ngram_range = (1,1),tokenizer = token.tokenize)

In [26]:
text = cv.fit_transform(data['tweet'])

C:\Users\ssanj\anaconda3\Lib\site-packages\sklearn\feature_extraction\text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [27]:
X_train, X_test, Y_train, Y_test = train_test_split(text, data['label'], test_size=0.3, random_state=5)

In [28]:
MNB = MultinomialNB()
MNB.fit(X_train, Y_train)

MultinomialNB()

In [29]:
predicted = MNB.predict(X_test)

In [30]:
accuracy_score = metrics.accuracy_score(predicted, Y_test)
print("Accuracy Score: ",accuracy_score)

Accuracy Score:  0.5165745856353591