In [1]:
import pandas as pd

# Random Mask Fill

In [2]:
data = pd.read_csv('yor_train_rand.tsv', sep="\t")

In [3]:
data

,tweet,label,ID
0,w ik pn abaradd w o e re o O dr o k o mni re...,negative,NaN
1,Yorb nbyn y wanle b k bnj ha eebu Yoruba,negative,NaN
2,we gb n mlm l rn n d lru w fn wn p k wn r...,negative,NaN
3,RT asa kasa ti awon eyan ko ni odo awon oyin...,negative,NaN
4,RT Mo r wn b kkan ti wn t wn fi w e yy fiw...,negative,NaN
...,...,...,...
10221,HIVAIDS nkan k ni gbgn o rn p lde n t wn alsn ...,negative,yor_train_05002
10222,RT A j p mo dp fld t kust k w sl wy dn mj a tn...,positive,yor_train_05003
10223,Mo wa ko si Dutch K y mi O k l ceram Dutch,neutral,yor_train_05004
10224,j mrin ni js nl Yorb kumuamini wn b s n e OsuL...,neutral,yor_train_05005
10225,Yob n k tn w rees k s w tn lw fi nm mi na ti t...,positive,yor_train_05006

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
from nltk.tokenize import RegexpTokenizer

In [5]:
token = RegexpTokenizer(r'[a-zA-Z0-9]+')
cv = CountVectorizer(stop_words='english',ngram_range = (1,1),tokenizer = token.tokenize)

In [6]:
text = cv.fit_transform(data['tweet'])

C:\Users\ssanj\anaconda3\Lib\site-packages\sklearn\feature_extraction\text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(text, data['label'], test_size=0.3, random_state=5)

# Using Multinomial NB for Sentiment Analysis on Augmented Data

In [8]:
from sklearn.naive_bayes import MultinomialNB
MNB = MultinomialNB()
MNB.fit(X_train, Y_train)

MultinomialNB()

In [9]:
from sklearn import metrics
predicted = MNB.predict(X_test)

In [10]:
accuracy_score = metrics.accuracy_score(predicted, Y_test)
print("Accuracy Score: ",accuracy_score)

Accuracy Score:  0.6916558018252934

# Without Augmentation

In [11]:
train_data = pd.read_csv("yor_train.tsv", sep="\t")
train_data

                                                  tweet     label
0     Ìwọ ikú òpònú abaradúdú wọ, o ò ṣe é 're o. O ...  negative
1     Yorùbá nbú'yàn ṣá """"""""..àyà wanle bí òkú ì...  negative
2     Òwe àgbà ní """"""""ọmọlọ́mọ là á rán níṣẹ́ à ...  negative
3     RT @user: @user asa kasa ti awon eyan ko ni od...  negative
4     RT @user: Mo ń rí àwọn èébú kọ̀ọ̀kan. Àti àwọn...  negative
...                                                 ...       ...
8517  RT @user: Oju adan o'nribi, oju awodi o'nri or...  positive
8518  a tú dúpẹ́ lọ́wọ́ àwọn alátakò wá náà, a ó gbọ...  positive
8519  Ẹní tó làná, tó lòní, kò leè lọ̀la; Ọlọ́run nì...  positive
8520  My God is """"""""onise iyanu"""""""" ( A Mira...  positive
8521  RT @user: Ẹ wá ba mi re! #yorubafood #naijafoo...  positive

[8522 rows x 2 columns]

In [12]:
import re

In [13]:
def clean_text(text):

    text = re.sub(r'http\S+|www.\S+|@\w+', '', text)
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    text = text.strip()
    
    return text

In [14]:
train_data['tweet'] = train_data['tweet'].apply(clean_text)

In [15]:
train_data['tweet']

0       w ik pn abaradd w o  e  re o O dr o k o mni re...
1              Yorb nbyn  y wanle b k bnj ha  eebu Yoruba
2       we gb n mlm l  rn n   d lru  w fn wn p k wn  r...
3       RT   asa kasa ti awon eyan ko ni odo awon oyin...
4       RT  Mo  r wn b kkan ti wn t wn  fi w e yy  fiw...
                              ...
8517    RT  Oju adan onribi oju awodi onri oran loni o...
8518    a t dp lw wn altak w n a  gbn tn bni a  m tn a...
8519    n t ln t ln k le lla lrun nkan l lj gbogbo  Wh...
8520       My God is onise iyanu  A Miracle Worker yoruba
8521     RT   w ba mi re yorubafood naijafood africanfood
Name: tweet, Length: 8522, dtype: object

In [16]:
texts = cv.fit_transform(train_data['tweet'])

C:\Users\ssanj\anaconda3\Lib\site-packages\sklearn\feature_extraction\text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [17]:
X_train, X_test, Y_train, Y_test = train_test_split(texts, train_data['label'], test_size=0.3, random_state=5)

In [18]:
from sklearn.naive_bayes import MultinomialNB
MNB = MultinomialNB()
MNB.fit(X_train, Y_train)

MultinomialNB()

In [19]:
from sklearn import metrics
predicted = MNB.predict(X_test)

In [20]:
accuracy_score = metrics.accuracy_score(predicted, Y_test)
print("Accuracy Score: ",accuracy_score)

Accuracy Score:  0.6726632772780602

In [21]:
from sklearn.metrics import classification_report

In [22]:
print(classification_report(Y_test, predicted))

              precision    recall  f1-score   support

    negative       0.63      0.34      0.44       544
     neutral       0.63      0.76      0.69       932
    positive       0.73      0.76      0.75      1081

    accuracy                           0.67      2557
   macro avg       0.66      0.62      0.63      2557
weighted avg       0.67      0.67      0.66      2557

# Iterative Mask Fill

In [23]:
data = pd.read_csv('yor_train_iter.tsv', sep="\t")

In [24]:
data

,tweet,label,ID
0,w ik pn abaradd w o e re o O dr o k o mni re...,negative,NaN
1,Yorb nbyn y wanle b k bnj ha eebu Yoruba,negative,NaN
2,we gb n mlm l rn n d lru w fn wn p k wn r...,negative,NaN
3,RT asa kasa ti awon eyan ko ni odo awon oyin...,negative,NaN
4,RT Mo r wn b kkan ti wn t wn fi w e yy fiw...,negative,NaN
...,...,...,...
10221,bril inperking ##wandalia kuas inperking kuas ...,negative,yor_train_05002
10222,bril kuas inperking inperking kuas kumuapisha ...,positive,yor_train_05003
10223,##gero inperking kuas inperking standbeeld sta...,neutral,yor_train_05004
10224,##wandalia rees kumuamini kumuamini kumuamini ...,neutral,yor_train_05005
10225,kuas inperking inperking kumuamini inperking s...,positive,yor_train_05006

In [25]:
token = RegexpTokenizer(r'[a-zA-Z0-9]+')
cv = CountVectorizer(stop_words='english',ngram_range = (1,1),tokenizer = token.tokenize)

In [26]:
text = cv.fit_transform(data['tweet'])

C:\Users\ssanj\anaconda3\Lib\site-packages\sklearn\feature_extraction\text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [27]:
X_train, X_test, Y_train, Y_test = train_test_split(text, data['label'], test_size=0.3, random_state=5)

In [28]:
MNB = MultinomialNB()
MNB.fit(X_train, Y_train)

MultinomialNB()

In [29]:
predicted = MNB.predict(X_test)

In [30]:
accuracy_score = metrics.accuracy_score(predicted, Y_test)
print("Accuracy Score: ",accuracy_score)

Accuracy Score:  0.6267926988265972