In [1]:
import pandas as pd

# Random Mask Fill

In [2]:
data = pd.read_csv('kr_train_rand.tsv', sep="\t")

In [3]:
data

,ID,tweet,label
0,kr_train_00001,Hhhhhh ntabyihogoza ubu x abo yishe bangana ik,negative
1,kr_train_00002,Amahano Ni impanuka inkangu inzara Muyite izin...,negative
2,kr_train_00003,Ese umuntu aguhaye miliyoni 7 zidorali ngo ary...,negative
3,kr_train_00004,Ugira amagambo kandi Ubwo wasanga nawe byaguta...,negative
4,kr_train_00005,Ukuntu inama zose zikomeye zirikubera Mu Rwand...,negative
...,...,...,...
3957,kr_train_03958,Umwana uzi ubwenge bamusiga kunyunyi yinogereza,positive
3958,kr_train_03959,Ni fighter mumaraso Amazuru yabo abayarasabits...,negative
3959,kr_train_03960,Urebe ibyo yagiye yivugira nyamara ntimugapfe ...,negative
3960,kr_train_03961,Nibyo kabsa bro Aho tubyumva kimwe tanu ##wate...,positive
3961,kr_train_03962,Uyu muvugo alaf mbona volume,neutral

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
from nltk.tokenize import RegexpTokenizer

In [5]:
token = RegexpTokenizer(r'[a-zA-Z0-9]+')
cv = CountVectorizer(stop_words='english',ngram_range = (1,1),tokenizer = token.tokenize)

In [6]:
text = cv.fit_transform(data['tweet'])

C:\Users\ssanj\anaconda3\Lib\site-packages\sklearn\feature_extraction\text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(text, data['label'], test_size=0.3, random_state=5)

# Using Multinomial NB for Sentiment Analysis on Augmented Data

In [8]:
from sklearn.naive_bayes import MultinomialNB
MNB = MultinomialNB()
MNB.fit(X_train, Y_train)

MultinomialNB()

In [9]:
from sklearn import metrics
predicted = MNB.predict(X_test)

In [10]:
accuracy_score = metrics.accuracy_score(predicted, Y_test)
print("Accuracy Score: ",accuracy_score)

Accuracy Score:  0.6930193439865433

# Without Augmentation

In [11]:
train_data = pd.read_csv("kr_train.tsv", sep="\t")
train_data

,ID,tweet,label
0,kr_train_00001,@user @user @user @user @user @user @user Hhhh...,negative
1,kr_train_00002,"@user Amahano?! Ni impanuka, inkangu, inzara.....",negative
2,kr_train_00003,Ese umuntu aguhaye miliyoni 7 zidorali ngo ary...,negative
3,kr_train_00004,Ugira amagambo😏 kandi Ubwo wasanga nawe byagut...,negative
4,kr_train_00005,Ukuntu inama zose zikomeye zirikubera Mu Rwand...,negative
...,...,...,...
3297,kr_train_03298,"Tugukunda kurusha mukobwa mwiza! Amahoro, ibyi...",positive
3298,kr_train_03299,*Sobanukirwa IBYIZA MASSAGE IFITEYE UMUBIRI* 👉...,positive
3299,kr_train_03300,Mushobora kugira uruhare muri iki kiganiro mut...,positive
3300,kr_train_03301,"2/2 Ntuduhane mu bitwoshya, Ahubwo udukize Umu...",positive
3301,kr_train_03302,@user @user @user @user @user @user Ni umuyobo...,positive

In [12]:
import re

In [13]:
def clean_text(text):

    text = re.sub(r'http\S+|www.\S+|@\w+', '', text)
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    text = text.strip()
    
    return text

In [14]:
train_data['tweet'] = train_data['tweet'].apply(clean_text)

In [15]:
train_data['tweet']

0          Hhhhhh ntabyihogoza ubu x abo yishe bangana ik
1       Amahano Ni impanuka inkangu inzara Muyite izin...
2       Ese umuntu aguhaye miliyoni 7 zidorali ngo ary...
3       Ugira amagambo kandi Ubwo wasanga nawe byaguta...
4       Ukuntu inama zose zikomeye zirikubera Mu Rwand...
                              ...
3297    Tugukunda kurusha mukobwa mwiza Amahoro ibyish...
3298    Sobanukirwa IBYIZA MASSAGE IFITEYE UMUBIRI   h...
3299    Mushobora kugira uruhare muri iki kiganiro mut...
3300    22 Ntuduhane mu bitwoshya Ahubwo udukize Umubi...
3301    Ni umuyobozi wintangarugero aho ageze hose Ni ...
Name: tweet, Length: 3302, dtype: object

In [16]:
texts = cv.fit_transform(train_data['tweet'])

C:\Users\ssanj\anaconda3\Lib\site-packages\sklearn\feature_extraction\text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [17]:
X_train, X_test, Y_train, Y_test = train_test_split(texts, train_data['label'], test_size=0.3, random_state=5)

In [18]:
from sklearn.naive_bayes import MultinomialNB
MNB = MultinomialNB()
MNB.fit(X_train, Y_train)

MultinomialNB()

In [19]:
from sklearn import metrics
predicted = MNB.predict(X_test)

In [20]:
accuracy_score = metrics.accuracy_score(predicted, Y_test)
print("Accuracy Score: ",accuracy_score)

Accuracy Score:  0.5721493440968718

In [21]:
from sklearn.metrics import classification_report

In [22]:
print(classification_report(Y_test, predicted))

              precision    recall  f1-score   support

    negative       0.55      0.63      0.59       336
     neutral       0.56      0.55      0.55       373
    positive       0.63      0.54      0.58       282

    accuracy                           0.57       991
   macro avg       0.58      0.57      0.57       991
weighted avg       0.58      0.57      0.57       991

# Iterative Mask Fill

In [23]:
data = pd.read_csv('kr_train_iter.tsv', sep="\t")

In [24]:
data

,ID,tweet,label
0,kr_train_00001,Hhhhhh ntabyihogoza ubu x abo yishe bangana ik,negative
1,kr_train_00002,Amahano Ni impanuka inkangu inzara Muyite izin...,negative
2,kr_train_00003,Ese umuntu aguhaye miliyoni 7 zidorali ngo ary...,negative
3,kr_train_00004,Ugira amagambo kandi Ubwo wasanga nawe byaguta...,negative
4,kr_train_00005,Ukuntu inama zose zikomeye zirikubera Mu Rwand...,negative
...,...,...,...
3957,kr_train_03958,ulipangwa ommy fighter fighter ommy cop,positive
3958,kr_train_03959,ulipangwa ommy limu fighter wafana gewag lafi ...,negative
3959,kr_train_03960,behavior wafana wafana wafana wafana wafana wa...,negative
3960,kr_train_03961,##nin grana viewers limu broadcast limu ulipan...,positive
3961,kr_train_03962,##washu wafana broadcast panel lafi,neutral

In [25]:
token = RegexpTokenizer(r'[a-zA-Z0-9]+')
cv = CountVectorizer(stop_words='english',ngram_range = (1,1),tokenizer = token.tokenize)

In [26]:
text = cv.fit_transform(data['tweet'])

C:\Users\ssanj\anaconda3\Lib\site-packages\sklearn\feature_extraction\text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [27]:
X_train, X_test, Y_train, Y_test = train_test_split(text, data['label'], test_size=0.3, random_state=5)

In [28]:
MNB = MultinomialNB()
MNB.fit(X_train, Y_train)

MultinomialNB()

In [29]:
predicted = MNB.predict(X_test)

In [30]:
accuracy_score = metrics.accuracy_score(predicted, Y_test)
print("Accuracy Score: ",accuracy_score)

Accuracy Score:  0.5693860386879731