In [1]:
import pandas as pd

# Random Mask Fill

In [2]:
data = pd.read_csv('orm_train_rand.tsv', sep="\t")

In [3]:
data

,ID,tweet,label
0,or_test_00001,Obbo shimallis ummanni keenya kan Wolloo dhuma...,neutral
1,or_test_00002,Kanuma dubbiinGuyyaatti YouTube altokkollee ta...,negative
2,or_test_00003,Kan Ofbeekukan waan isaa Beekudabree waan Alag...,positive
3,or_test_00004,Gafa Abyii aangoo qabatee jalqabee deemsii isa...,negative
4,or_test_00005,Sabni keenya akkuma tokkummaan kaee safaricom ...,positive
...,...,...,...
3139,orm_train_04346,Doofaagowwaawallaalaakan akka harreetti yaaduk...,negative
3140,orm_train_04347,Uummati oromoo naanoo oromiyaa boorana Gujii w...,negative
3141,orm_train_04348,Dhugumatti Jawar Mohammed nama kutannoonummata...,neutral
3142,orm_train_04349,Jioota 3 as deemu keesaatti yoo ##hihisha maka...,negative
3143,orm_train_04350,beber hedduun baqatee kan bineensi nyaate lakk...,negative

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
from nltk.tokenize import RegexpTokenizer

In [5]:
token = RegexpTokenizer(r'[a-zA-Z0-9]+')
cv = CountVectorizer(stop_words='english',ngram_range = (1,1),tokenizer = token.tokenize)

In [6]:
text = cv.fit_transform(data['tweet'])

C:\Users\ssanj\anaconda3\Lib\site-packages\sklearn\feature_extraction\text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(text, data['label'], test_size=0.3, random_state=5)

# Using Multinomial NB for Sentiment Analysis on Augmented Data

In [8]:
from sklearn.naive_bayes import MultinomialNB
MNB = MultinomialNB()
MNB.fit(X_train, Y_train)

MultinomialNB()

In [9]:
from sklearn import metrics
predicted = MNB.predict(X_test)

In [10]:
accuracy_score = metrics.accuracy_score(predicted, Y_test)
print("Accuracy Score: ",accuracy_score)

Accuracy Score:  0.6663135593220338

# Without Augmentation

In [11]:
train_data = pd.read_csv("orm_train.tsv", sep="\t")
train_data

,ID,tweet,label
0,or_test_00001,@user Obbo shimallis ummanni keenya kan Wolloo...,neutral
1,or_test_00002,@user Kanuma dubbiin!Guyyaatti YouTube altokko...,negative
2,or_test_00003,"Kan Of-beeku,kan waan isaa Beeku,dabree waan A...",positive
3,or_test_00004,Gafa Abyii aangoo qabatee jalqabee deemsii isa...,negative
4,or_test_00005,Sabni keenya akkuma tokkummaan ka'ee safaricom...,positive
...,...,...,...
2091,or_test_02092,@user Waraana Mootummaa fi Uummata gidduutti t...,neutral
2092,or_test_02093,"Mootummaan Xoophiyaa ,waraana #ABO , barbaach...",neutral
2093,or_test_02094,@user @user waraana mootummaadha moo kan qabe?,positive
2094,or_test_02095,@user---========Godina Shawaa Kaabaa Aanaa War...,positive
2095,or_test_02096,Yoo itti beekan akka goota kanaati yoo itti wa...,positive

In [12]:
import re

In [13]:
def clean_text(text):

    text = re.sub(r'http\S+|www.\S+|@\w+', '', text)
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    text = text.strip()
    
    return text

In [14]:
train_data['tweet'] = train_data['tweet'].apply(clean_text)

In [15]:
train_data['tweet']

0       Obbo shimallis ummanni keenya kan Wolloo dhuma...
1       Kanuma dubbiinGuyyaatti YouTube altokkollee ta...
2       Kan Ofbeekukan waan isaa Beekudabree waan Alag...
3       Gafa Abyii aangoo qabatee jalqabee deemsii isa...
4       Sabni keenya akkuma tokkummaan kaee safaricom ...
                              ...
2091    Waraana Mootummaa fi Uummata gidduutti taasifa...
2092    Mootummaan Xoophiyaa waraana  ABO  barbaacha L...
2093                    waraana mootummaadha moo kan qabe
2094    Godina Shawaa Kaabaa Aanaa Warra Jaarsootti mi...
2095    Yoo itti beekan akka goota kanaati yoo itti wa...
Name: tweet, Length: 2096, dtype: object

In [16]:
texts = cv.fit_transform(train_data['tweet'])

C:\Users\ssanj\anaconda3\Lib\site-packages\sklearn\feature_extraction\text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [17]:
X_train, X_test, Y_train, Y_test = train_test_split(texts, train_data['label'], test_size=0.3, random_state=5)

In [18]:
from sklearn.naive_bayes import MultinomialNB
MNB = MultinomialNB()
MNB.fit(X_train, Y_train)

MultinomialNB()

In [19]:
from sklearn import metrics
predicted = MNB.predict(X_test)

In [20]:
accuracy_score = metrics.accuracy_score(predicted, Y_test)
print("Accuracy Score: ",accuracy_score)

Accuracy Score:  0.4356120826709062

In [21]:
from sklearn.metrics import classification_report

In [22]:
print(classification_report(Y_test, predicted))

              precision    recall  f1-score   support

    negative       0.41      0.46      0.44       218
     neutral       0.47      0.54      0.50       267
    positive       0.36      0.20      0.26       144

    accuracy                           0.44       629
   macro avg       0.42      0.40      0.40       629
weighted avg       0.43      0.44      0.42       629

# Iterative Mask Fill

In [25]:
data = pd.read_csv('orm_train_iter.tsv', sep="\t")

In [26]:
data

,ID,tweet,label
0,or_test_00001,Obbo shimallis ummanni keenya kan Wolloo dhuma...,neutral
1,or_test_00002,Kanuma dubbiinGuyyaatti YouTube altokkollee ta...,negative
2,or_test_00003,Kan Ofbeekukan waan isaa Beekudabree waan Alag...,positive
3,or_test_00004,Gafa Abyii aangoo qabatee jalqabee deemsii isa...,negative
4,or_test_00005,Sabni keenya akkuma tokkummaan kaee safaricom ...,positive
...,...,...,...
3139,orm_train_04346,beber bahasa outing ##hihisha ##hihisha ##guri...,negative
3140,orm_train_04347,beber tadi mwawe unaeza beber ##hihisha ##koso...,negative
3141,orm_train_04348,beber tadi ##kosoa ##hihisha ##hihisha ##ggle ...,neutral
3142,orm_train_04349,unaeza amphibi mwawe ##guri ##guri ##ggle ##hi...,negative
3143,orm_train_04350,beber bahasa bahasa ##ggle 5123 tugu theft ##j...,negative

In [27]:
token = RegexpTokenizer(r'[a-zA-Z0-9]+')
cv = CountVectorizer(stop_words='english',ngram_range = (1,1),tokenizer = token.tokenize)

In [28]:
text = cv.fit_transform(data['tweet'])

C:\Users\ssanj\anaconda3\Lib\site-packages\sklearn\feature_extraction\text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [29]:
X_train, X_test, Y_train, Y_test = train_test_split(text, data['label'], test_size=0.3, random_state=5)

In [30]:
MNB = MultinomialNB()
MNB.fit(X_train, Y_train)

MultinomialNB()

In [31]:
predicted = MNB.predict(X_test)

In [32]:
accuracy_score = metrics.accuracy_score(predicted, Y_test)
print("Accuracy Score: ",accuracy_score)

Accuracy Score:  0.475635593220339