In [2]:
import pandas as pd

# Random Mask Fill

In [3]:
data = pd.read_csv('twi_train_rand.tsv', sep="\t")

In [4]:
data

,tweet,label,ID
0,kako be shark but wo ti ewu,negative,NaN
1,br ne bayie nti na me supporti man city,negative,NaN
2,s3 woofis3 mada wafutuo tantan no 3y3wo s3mafa...,negative,NaN
3,wabdam anaa wo trumu y nkate nkwan ase,negative,NaN
4,enfa bi da bra,negative,NaN
...,...,...,...
4172,ghana boy s menni hwee koraa na nny me tupeane,positive,twi_train_03994
4173,keegan ##chakaa anka dubai fa woho b3n anka wo...,negative,twi_train_03995
4174,bavandimwe mo nim s3 3korso,positive,twi_train_03996
4175,abou nso mafe wo dodo,positive,twi_train_03997
4176,hahaha wie lein de gye cup,negative,twi_train_03998

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
from nltk.tokenize import RegexpTokenizer

In [6]:
token = RegexpTokenizer(r'[a-zA-Z0-9]+')
cv = CountVectorizer(stop_words='english',ngram_range = (1,1),tokenizer = token.tokenize)

In [7]:
text = cv.fit_transform(data['tweet'])

C:\Users\ssanj\anaconda3\Lib\site-packages\sklearn\feature_extraction\text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(text, data['label'], test_size=0.3, random_state=5)

# Using Multinomial NB for Sentiment Analysis on Augmented Data

In [9]:
from sklearn.naive_bayes import MultinomialNB
MNB = MultinomialNB()
MNB.fit(X_train, Y_train)

MultinomialNB()

In [10]:
from sklearn import metrics
predicted = MNB.predict(X_test)

In [11]:
accuracy_score = metrics.accuracy_score(predicted, Y_test)
print("Accuracy Score: ",accuracy_score)

Accuracy Score:  0.6323763955342903

# Without Augmentation

In [12]:
train_data = pd.read_csv("twi_train.tsv", sep="\t")
train_data

                                                  tweet     label
0                           kako be shark but wo ti ewu  negative
1               br ne bayie nti na me supporti man city  negative
2     s3 woofis3 mada wafutuo tantan no 3y3wo s3mafa...  negative
3             wabɔdam anaa wo trumu yɛ nkate nkwan aseɛ  negative
4                                     enfa bi da bra 🤣🤣  negative
...                                                 ...       ...
3476                kasa gu ma sum na me gyedi 🔥🔥🔥🔥🔥🔥🔥🔥  positive
3477                         asa oo 3bi ansu wo so kcda  positive
3478   ah ah ah so naaaa kwadwo piano take start o hmmm  positive
3479                        3nam mo asa nti b3gye kosua  positive
3480                    eeii my wife 3no mpo na mep3 no  positive

[3481 rows x 2 columns]

In [13]:
import re

In [14]:
def clean_text(text):

    text = re.sub(r'http\S+|www.\S+|@\w+', '', text)
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    text = text.strip()
    
    return text

In [15]:
train_data['tweet'] = train_data['tweet'].apply(clean_text)

In [16]:
train_data['tweet']

0                             kako be shark but wo ti ewu
1                 br ne bayie nti na me supporti man city
2       s3 woofis3 mada wafutuo tantan no 3y3wo s3mafa...
3                  wabdam anaa wo trumu y nkate nkwan ase
4                                          enfa bi da bra
                              ...
3476                           kasa gu ma sum na me gyedi
3477                           asa oo 3bi ansu wo so kcda
3478     ah ah ah so naaaa kwadwo piano take start o hmmm
3479                          3nam mo asa nti b3gye kosua
3480                      eeii my wife 3no mpo na mep3 no
Name: tweet, Length: 3481, dtype: object

In [17]:
texts = cv.fit_transform(train_data['tweet'])

C:\Users\ssanj\anaconda3\Lib\site-packages\sklearn\feature_extraction\text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [18]:
X_train, X_test, Y_train, Y_test = train_test_split(texts, train_data['label'], test_size=0.3, random_state=5)

In [19]:
from sklearn.naive_bayes import MultinomialNB
MNB = MultinomialNB()
MNB.fit(X_train, Y_train)

MultinomialNB()

In [20]:
from sklearn import metrics
predicted = MNB.predict(X_test)

In [21]:
accuracy_score = metrics.accuracy_score(predicted, Y_test)
print("Accuracy Score: ",accuracy_score)

Accuracy Score:  0.6095693779904306

In [22]:
from sklearn.metrics import classification_report

In [23]:
print(classification_report(Y_test, predicted))

              precision    recall  f1-score   support

    negative       0.63      0.68      0.65       398
     neutral       0.27      0.09      0.13       163
    positive       0.63      0.73      0.67       484

    accuracy                           0.61      1045
   macro avg       0.51      0.50      0.49      1045
weighted avg       0.57      0.61      0.58      1045

# Iterative Mask Fill

In [24]:
data = pd.read_csv('twi_train_iter.tsv', sep="\t")

In [25]:
data

,tweet,label,ID
0,kako be shark but wo ti ewu,negative,NaN
1,br ne bayie nti na me supporti man city,negative,NaN
2,s3 woofis3 mada wafutuo tantan no 3y3wo s3mafa...,negative,NaN
3,wabdam anaa wo trumu y nkate nkwan ase,negative,NaN
4,enfa bi da bra,negative,NaN
...,...,...,...
4172,nukta abou abou abou abou abou abou abou abou ...,positive,twi_train_03994
4173,kusaliti abou abou abou abou abou abou abou ab...,negative,twi_train_03995
4174,bavandimwe abou abou abou abou,positive,twi_train_03996
4175,abou abou abou abou abou,positive,twi_train_03997
4176,##unganishe abou abou abou abou abou,negative,twi_train_03998

In [26]:
token = RegexpTokenizer(r'[a-zA-Z0-9]+')
cv = CountVectorizer(stop_words='english',ngram_range = (1,1),tokenizer = token.tokenize)

In [27]:
text = cv.fit_transform(data['tweet'])

C:\Users\ssanj\anaconda3\Lib\site-packages\sklearn\feature_extraction\text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [28]:
X_train, X_test, Y_train, Y_test = train_test_split(text, data['label'], test_size=0.3, random_state=5)

In [29]:
MNB = MultinomialNB()
MNB.fit(X_train, Y_train)

MultinomialNB()

In [30]:
predicted = MNB.predict(X_test)

In [31]:
accuracy_score = metrics.accuracy_score(predicted, Y_test)
print("Accuracy Score: ",accuracy_score)

Accuracy Score:  0.562200956937799