In [1]:
import pandas as pd

# Random Mask Fill

In [33]:
data = pd.read_csv('hau_train_rand.tsv', sep="\t")

In [42]:
data=data.dropna(subset=['tweet'])

In [60]:
data

,tweet,label,ID
0,Da kudin da Arewa babu wani abin azo agani da ...,negative,NaN
1,Kaga wani Adu ar Banda wai a haka Shi ne shuga...,negative,NaN
2,Sai haquri fa yan madrid daman kunce champion ...,negative,NaN
3,Hmmm yanzu kai kasan girman allah daxakace muk...,negative,NaN
4,Wai gwamno nin Nigeria suna afa kwayoyi ko,negative,NaN
...,...,...,...
14733,dribble dribble dribble vileo vileo dribble ut...,negative,hau_train_03864
14734,brands dribble dribble dribble,positive,hau_train_03865
14735,dribble dribble dribble dribble dribble dribbl...,positive,hau_train_03866
14736,dribble dribble dribble,positive,hau_train_03867
14737,dribble kuletewa kuletewa dribble dribble dribble,neutral,hau_train_03868

In [43]:
from sklearn.feature_extraction.text import CountVectorizer
from nltk.tokenize import RegexpTokenizer

In [44]:
token = RegexpTokenizer(r'[a-zA-Z0-9]+')
cv = CountVectorizer(stop_words='english',ngram_range = (1,1),tokenizer = token.tokenize)

In [45]:
text = cv.fit_transform(data['tweet'])

C:\Users\ssanj\anaconda3\Lib\site-packages\sklearn\feature_extraction\text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [46]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(text, data['label'], test_size=0.3, random_state=5)

# Using Multinomial NB for Sentiment Analysis on Augmented Data

In [47]:
from sklearn.naive_bayes import MultinomialNB
MNB = MultinomialNB()
MNB.fit(X_train, Y_train)

MultinomialNB()

In [48]:
from sklearn import metrics
predicted = MNB.predict(X_test)

In [49]:
accuracy_score = metrics.accuracy_score(predicted, Y_test)
print("Accuracy Score: ",accuracy_score)

Accuracy Score:  0.6973535399230943

# Without Augmentation

In [9]:
train_data = pd.read_csv("hau_train.tsv", sep="\t")
train_data

                                                   tweet     label
0      @user Da kudin da Arewa babu wani abin azo aga...  negative
1      @user Kaga wani Adu ar Banda💔😭 wai a haka Shi ...  negative
2      @user Sai haquri fa yan madrid daman kunce cha...  negative
3      @user Hmmm yanzu kai kasan girman allah daxaka...  negative
4      @user @user Wai gwamno nin Nigeria suna afa kw...  negative
...                                                  ...       ...
14167  @user Ba wasa a fuskokinsu, may you succeed al...  positive
14168         @user Allah yasa muyi kyakkyawan qarshe 🤲🤲  positive
14169  @user Abu nafarko gamawa da duniya lafiya kuma...  positive
14170  @user @user @user Allah ubangiji yaiwa rayuwar...  positive
14171  @user @user Baka film din banza director Allah...  positive

[14172 rows x 2 columns]

In [10]:
import re

In [11]:
def clean_text(text):

    text = re.sub(r'http\S+|www.\S+|@\w+', '', text)
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    text = text.strip()
    
    return text

In [12]:
train_data['tweet'] = train_data['tweet'].apply(clean_text)

In [13]:
train_data['tweet']

0        Da kudin da Arewa babu wani abin azo agani da ...
1        Kaga wani Adu ar Banda wai a haka Shi ne shuga...
2        Sai haquri fa yan madrid daman kunce champion ...
3        Hmmm yanzu kai kasan girman allah daxakace muk...
4               Wai gwamno nin Nigeria suna afa kwayoyi ko
                               ...
14167     Ba wasa a fuskokinsu may you succeed always guys
14168                    Allah yasa muyi kyakkyawan qarshe
14169    Abu nafarko gamawa da duniya lafiya kuma inaso...
14170               Allah ubangiji yaiwa rayuwarsa albarka
14171    Baka film din banza director Allah ya dafa ni ...
Name: tweet, Length: 14172, dtype: object

In [14]:
texts = cv.fit_transform(train_data['tweet'])

C:\Users\ssanj\anaconda3\Lib\site-packages\sklearn\feature_extraction\text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test, Y_train, Y_test = train_test_split(texts, train_data['label'], test_size=0.3, random_state=5)

In [18]:
from sklearn.naive_bayes import MultinomialNB
MNB = MultinomialNB()
MNB.fit(X_train, Y_train)

MultinomialNB()

In [19]:
from sklearn import metrics
predicted = MNB.predict(X_test)

In [20]:
accuracy_score = metrics.accuracy_score(predicted, Y_test)
print("Accuracy Score: ",accuracy_score)

Accuracy Score:  0.6970837253057385

In [21]:
from sklearn.metrics import classification_report

In [22]:
print(classification_report(Y_test, predicted))

              precision    recall  f1-score   support

    negative       0.62      0.74      0.68      1396
     neutral       0.67      0.57      0.62      1437
    positive       0.81      0.79      0.80      1419

    accuracy                           0.70      4252
   macro avg       0.70      0.70      0.70      4252
weighted avg       0.70      0.70      0.70      4252

# Iterative Mask Fill

In [50]:
data = pd.read_csv('hau_train_iter.tsv', sep="\t")

In [53]:
data=data.dropna(subset=['tweet'])

In [54]:
token = RegexpTokenizer(r'[a-zA-Z0-9]+')
cv = CountVectorizer(stop_words='english',ngram_range = (1,1),tokenizer = token.tokenize)

In [55]:
text = cv.fit_transform(data['tweet'])

C:\Users\ssanj\anaconda3\Lib\site-packages\sklearn\feature_extraction\text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [56]:
X_train, X_test, Y_train, Y_test = train_test_split(text, data['label'], test_size=0.3, random_state=5)

In [57]:
MNB = MultinomialNB()
MNB.fit(X_train, Y_train)

MultinomialNB()

In [58]:
predicted = MNB.predict(X_test)

In [59]:
accuracy_score = metrics.accuracy_score(predicted, Y_test)
print("Accuracy Score: ",accuracy_score)

Accuracy Score:  0.6763175752092286